CREATE DATABASE TRAINING_DB;

CREATE SCHEMA TRAINING_DB.NETFLIX_SC;

SELECT * FROM INFORMATION_SCHEMA.TABLES;

CREATE TABLE TRAINING_DB.NETFLIX_SC.NETFLIX_DATASET;
SELECT * FROM TRAINING_DB.NETFLIX_SC.NETFLIX_DATASET

SELECT COUNT(*) FROM TRAINING_DB.NETFLIX_SC.NETFLIX_DATASET

